// word pairs by language — { civilian, impostor }
// fallback: if lang not supported, defaults to 'en'

export const WORD_PAIRS = {
    fr: [
        // animaux
        { civilian: "Lion", impostor: "Tigre" },
        { civilian: "Dauphin", impostor: "Requin" },
        { civilian: "Cheval", impostor: "Âne" },
        { civilian: "Crocodile", impostor: "Alligator" },
        { civilian: "Pingouin", impostor: "Manchot" },
        { civilian: "Loup", impostor: "Chien" },
        { civilian: "Grenouille", impostor: "Crapaud" },
        { civilian: "Aigle", impostor: "Faucon" },
        { civilian: "Cobra", impostor: "Python" },
        { civilian: "Gorille", impostor: "Chimpanzé" },
        { civilian: "Panda", impostor: "Koala" },
        { civilian: "Renard", impostor: "Loup" },
        { civilian: "Pieuvre", impostor: "Calmar" },
        { civilian: "Bison", impostor: "Buffle" },
        { civilian: "Panthère", impostor: "Léopard" },
        // food
        { civilian: "Pizza", impostor: "Tarte flambée" },
        { civilian: "Sushi", impostor: "Maki" },
        { civilian: "Burger", impostor: "Sandwich" },
        { civilian: "Crêpe", impostor: "Gaufre" },
        { civilian: "Ramen", impostor: "Pho" },
        { civilian: "Tacos", impostor: "Burrito" },
        { civilian: "Croissant", impostor: "Pain au chocolat" },
        { civilian: "Lasagne", impostor: "Moussaka" },
        { civilian: "Kebab", impostor: "Shawarma" },
        { civilian: "Tiramisu", impostor: "Charlotte" },
        { civilian: "Fondue", impostor: "Raclette" },
        { civilian: "Quiche", impostor: "Tarte salée" },
        { civilian: "Soufflé", impostor: "Flan" },
        { civilian: "Brioche", impostor: "Pain brioché" },
        { civilian: "Éclair", impostor: "Chou à la crème" },
        // films / culture
        { civilian: "Titanic", impostor: "Pearl Harbor" },
        { civilian: "Avatar", impostor: "Dune" },
        { civilian: "Joker", impostor: "Batman" },
        { civilian: "Inception", impostor: "Interstellar" },
        { civilian: "Matrix", impostor: "Tron" },
        { civilian: "Toy Story", impostor: "Shrek" },
        { civilian: "Parasite", impostor: "Squid Game" },
        { civilian: "Jurassic Park", impostor: "King Kong" },
        { civilian: "Harry Potter", impostor: "Le Seigneur des Anneaux" },
        { civilian: "Fast and Furious", impostor: "Need for Speed" },
        { civilian: "Naruto", impostor: "Bleach" },
        { civilian: "One Piece", impostor: "Fairy Tail" },
        { civilian: "Dragon Ball", impostor: "Saint Seiya" },
        // sport
        { civilian: "Football", impostor: "Rugby" },
        { civilian: "Tennis", impostor: "Badminton" },
        { civilian: "Natation", impostor: "Water-polo" },
        { civilian: "Boxe", impostor: "MMA" },
        { civilian: "Cyclisme", impostor: "Triathlon" },
        { civilian: "Ski", impostor: "Snowboard" },
        { civilian: "Basket", impostor: "Handball" },
        { civilian: "Golf", impostor: "Pétanque" },
        { civilian: "Judo", impostor: "Karaté" },
        { civilian: "Volley", impostor: "Beach Volley" },
        { civilian: "Formule 1", impostor: "Moto GP" },
        { civilian: "Escrime", impostor: "Taekwondo" },
        // tech
        { civilian: "iPhone", impostor: "Samsung Galaxy" },
        { civilian: "Google", impostor: "Bing" },
        { civilian: "Instagram", impostor: "TikTok" },
        { civilian: "Netflix", impostor: "Disney+" },
        { civilian: "Twitch", impostor: "YouTube" },
        { civilian: "Discord", impostor: "Slack" },
        { civilian: "Minecraft", impostor: "Roblox" },
        { civilian: "PlayStation", impostor: "Xbox" },
        { civilian: "MacBook", impostor: "Surface" },
        { civilian: "ChatGPT", impostor: "Gemini" },
        { civilian: "Spotify", impostor: "Deezer" },
        { civilian: "Uber", impostor: "Bolt" },
        // lieux
        { civilian: "Plage", impostor: "Piscine" },
        { civilian: "Forêt", impostor: "Jungle" },
        { civilian: "Désert", impostor: "Steppe" },
        { civilian: "Montagne", impostor: "Colline" },
        { civilian: "Île", impostor: "Presqu'île" },
        { civilian: "Grotte", impostor: "Tunnel" },
        { civilian: "Volcan", impostor: "Geyser" },
        { civilian: "Lac", impostor: "Étang" },
        { civilian: "Cascade", impostor: "Fontaine" },
        { civilian: "Glacier", impostor: "Banquise" },
        // musique
        { civilian: "Guitare", impostor: "Basse" },
        { civilian: "Violon", impostor: "Alto" },
        { civilian: "Piano", impostor: "Synthétiseur" },
        { civilian: "Batterie", impostor: "Percussions" },
        { civilian: "Trompette", impostor: "Trombone" },
        { civilian: "Flûte", impostor: "Clarinette" },
        { civilian: "Accordéon", impostor: "Concertina" },
        // métiers
        { civilian: "Chirurgien", impostor: "Dentiste" },
        { civilian: "Pompier", impostor: "Policier" },
        { civilian: "Architecte", impostor: "Urbaniste" },
        { civilian: "Cuisinier", impostor: "Pâtissier" },
        { civilian: "Pilote", impostor: "Copilote" },
        { civilian: "Avocat", impostor: "Notaire" },
        { civilian: "Photographe", impostor: "Vidéaste" },
        // univers / fantastique
        { civilian: "Vampire", impostor: "Zombie" },
        { civilian: "Pirate", impostor: "Viking" },
        { civilian: "Astronaute", impostor: "Cosmonaute" },
        { civilian: "Chevalier", impostor: "Samouraï" },
        { civilian: "Robot", impostor: "Cyborg" },
        { civilian: "Dragon", impostor: "Wyverne" },
        { civilian: "Ninja", impostor: "Assassin" },
        // boissons
        { civilian: "Café", impostor: "Thé" },
        { civilian: "Bière", impostor: "Cidre" },
        { civilian: "Champagne", impostor: "Prosecco" },
        { civilian: "Whisky", impostor: "Bourbon" },
        { civilian: "Coca-Cola", impostor: "Pepsi" },
        { civilian: "Mojito", impostor: "Caïpirinha" },
        { civilian: "Smoothie", impostor: "Milkshake" },
    ],

    en: [
        // animals
        { civilian: "Lion", impostor: "Tiger" },
        { civilian: "Dolphin", impostor: "Shark" },
        { civilian: "Horse", impostor: "Donkey" },
        { civilian: "Crocodile", impostor: "Alligator" },
        { civilian: "Penguin", impostor: "Puffin" },
        { civilian: "Wolf", impostor: "Dog" },
        { civilian: "Frog", impostor: "Toad" },
        { civilian: "Eagle", impostor: "Hawk" },
        { civilian: "Cobra", impostor: "Python" },
        { civilian: "Gorilla", impostor: "Chimpanzee" },
        { civilian: "Panda", impostor: "Koala" },
        { civilian: "Fox", impostor: "Wolf" },
        { civilian: "Octopus", impostor: "Squid" },
        { civilian: "Bison", impostor: "Buffalo" },
        { civilian: "Panther", impostor: "Leopard" },
        // food
        { civilian: "Pizza", impostor: "Flatbread" },
        { civilian: "Sushi", impostor: "Maki" },
        { civilian: "Burger", impostor: "Sandwich" },
        { civilian: "Pancake", impostor: "Waffle" },
        { civilian: "Ramen", impostor: "Pho" },
        { civilian: "Tacos", impostor: "Burrito" },
        { civilian: "Croissant", impostor: "Pain au chocolat" },
        { civilian: "Lasagna", impostor: "Moussaka" },
        { civilian: "Kebab", impostor: "Shawarma" },
        { civilian: "Tiramisu", impostor: "Charlotte cake" },
        { civilian: "Hot dog", impostor: "Corn dog" },
        { civilian: "Brownie", impostor: "Blondie" },
        { civilian: "Bagel", impostor: "Donut" },
        { civilian: "Nachos", impostor: "Tortilla chips" },
        { civilian: "Cheesecake", impostor: "Key lime pie" },
        // movies / culture
        { civilian: "Titanic", impostor: "Pearl Harbor" },
        { civilian: "Avatar", impostor: "Dune" },
        { civilian: "Joker", impostor: "Batman" },
        { civilian: "Inception", impostor: "Interstellar" },
        { civilian: "The Matrix", impostor: "Tron" },
        { civilian: "Toy Story", impostor: "Shrek" },
        { civilian: "Parasite", impostor: "Squid Game" },
        { civilian: "Jurassic Park", impostor: "King Kong" },
        { civilian: "Harry Potter", impostor: "Lord of the Rings" },
        { civilian: "Fast and Furious", impostor: "Need for Speed" },
        { civilian: "Naruto", impostor: "Bleach" },
        { civilian: "One Piece", impostor: "Fairy Tail" },
        { civilian: "Breaking Bad", impostor: "Narcos" },
        // sport
        { civilian: "Soccer", impostor: "Rugby" },
        { civilian: "Tennis", impostor: "Badminton" },
        { civilian: "Swimming", impostor: "Water polo" },
        { civilian: "Boxing", impostor: "MMA" },
        { civilian: "Cycling", impostor: "Triathlon" },
        { civilian: "Skiing", impostor: "Snowboarding" },
        { civilian: "Basketball", impostor: "Handball" },
        { civilian: "Golf", impostor: "Disc golf" },
        { civilian: "Judo", impostor: "Karate" },
        { civilian: "Volleyball", impostor: "Beach volleyball" },
        { civilian: "Formula 1", impostor: "MotoGP" },
        { civilian: "Fencing", impostor: "Taekwondo" },
        // tech
        { civilian: "iPhone", impostor: "Samsung Galaxy" },
        { civilian: "Google", impostor: "Bing" },
        { civilian: "Instagram", impostor: "TikTok" },
        { civilian: "Netflix", impostor: "Disney+" },
        { civilian: "Twitch", impostor: "YouTube" },
        { civilian: "Discord", impostor: "Slack" },
        { civilian: "Minecraft", impostor: "Roblox" },
        { civilian: "PlayStation", impostor: "Xbox" },
        { civilian: "MacBook", impostor: "Surface" },
        { civilian: "ChatGPT", impostor: "Gemini" },
        { civilian: "Spotify", impostor: "Apple Music" },
        { civilian: "Uber", impostor: "Lyft" },
        // places
        { civilian: "Beach", impostor: "Swimming pool" },
        { civilian: "Forest", impostor: "Jungle" },
        { civilian: "Desert", impostor: "Steppe" },
        { civilian: "Mountain", impostor: "Hill" },
        { civilian: "Island", impostor: "Peninsula" },
        { civilian: "Cave", impostor: "Tunnel" },
        { civilian: "Volcano", impostor: "Geyser" },
        { civilian: "Lake", impostor: "Pond" },
        { civilian: "Waterfall", impostor: "Fountain" },
        { civilian: "Glacier", impostor: "Ice shelf" },
        // music
        { civilian: "Guitar", impostor: "Bass guitar" },
        { civilian: "Violin", impostor: "Viola" },
        { civilian: "Piano", impostor: "Synthesizer" },
        { civilian: "Drums", impostor: "Percussion" },
        { civilian: "Trumpet", impostor: "Trombone" },
        { civilian: "Flute", impostor: "Clarinet" },
        { civilian: "Accordion", impostor: "Concertina" },
        // jobs
        { civilian: "Surgeon", impostor: "Dentist" },
        { civilian: "Firefighter", impostor: "Police officer" },
        { civilian: "Architect", impostor: "Urban planner" },
        { civilian: "Chef", impostor: "Pastry chef" },
        { civilian: "Pilot", impostor: "Co-pilot" },
        { civilian: "Lawyer", impostor: "Notary" },
        { civilian: "Photographer", impostor: "Videographer" },
        // fantasy
        { civilian: "Vampire", impostor: "Zombie" },
        { civilian: "Pirate", impostor: "Viking" },
        { civilian: "Astronaut", impostor: "Cosmonaut" },
        { civilian: "Knight", impostor: "Samurai" },
        { civilian: "Robot", impostor: "Cyborg" },
        { civilian: "Dragon", impostor: "Wyvern" },
        { civilian: "Ninja", impostor: "Assassin" },
        // drinks
        { civilian: "Coffee", impostor: "Tea" },
        { civilian: "Beer", impostor: "Cider" },
        { civilian: "Champagne", impostor: "Prosecco" },
        { civilian: "Whiskey", impostor: "Bourbon" },
        { civilian: "Coca-Cola", impostor: "Pepsi" },
        { civilian: "Mojito", impostor: "Caipirinha" },
        { civilian: "Smoothie", impostor: "Milkshake" },
    ],
};

// detect language from browser, fallback to 'en'
export const detectLanguage = () => {
    const lang = navigator.language?.slice(0, 2).toLowerCase();
    return WORD_PAIRS[lang] ? lang : "en";
};

// pick a random pair from a given language pool
export const getRandomPair = (lang = "en") => {
    const pool = WORD_PAIRS[lang] ?? WORD_PAIRS["en"];
    return pool[Math.floor(Math.random() * pool.length)];
};